# Generated by Django 5.1.1 on 2024-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HolidayPlanner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                ("code", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("temp_min", models.FloatField()),
                ("temp_max", models.FloatField()),
                ("precip", models.FloatField()),
                ("precip_prob", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("wind_direction", models.CharField(max_length=20)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
